# 插件配置
# 例子
#limits:
#  MMOItems:
#    enable: true
#    # 限制器1 在world_nether 世界 和world世界中的(0,0,0) ~(100,255,100)的区域中 禁用/xxx generate 命令 使用正则表达式
#    limiter1:
#      enable: true
#      location:
#        - "world_nether"
#        - "world:0,0,0:100,255,100"
#      commands:
#        - "/.? generate.*"
#    # 限制器2 在非世界world中阻止 net.Indyuce.mmoitems.listener.ItemUse 中的 rightClickEffects(PlayerInteractEvent event) 监听器被调用
#    # 限制器2 在非世界world中阻止 net.Indyuce.mmoitems.listener.CraftingListener 中的所有监听器
#    # 限制器2 在非世界world中阻止 net.Indyuce.mmoitems.api.event.AbilityUseEvent 事件被call
#    limiter2:
#      enable: true
#      listeners:
#        net.Indyuce.mmoitems.listener.ItemUse:
#          - "rightClickEffects:org.bukkit.event.player.PlayerInteractEvent"
#        net.Indyuce.mmoitems.listener.CraftingListener: all
#      events:
#        - "net.Indyuce.mmoitems.api.event.AbilityUseEvent"
#      locations-R:
#        - world
Global:
  enable: true
  # 绕过登录、退出事件,以免玩家数据获取不到
  limiter1:
    enable: true
    eventsR:
      - org.bukkit.event.player.AsyncPlayerPreLoginEvent
      - org.bukkit.event.player.PlayerJoinEvent
      - org.bukkit.event.player.PlayerKickEvent
      - org.bukkit.event.player.PlayerLoginEvent
      - org.bukkit.event.player.PlayerPreLoginEvent
      - org.bukkit.event.player.PlayerQuitEvent
limits:


