name: PluginLimiter
main: top.iseason.bukkit.PluginLimiter
description: "限制插件功能"
version: 1.0
authors: [ Iseason ]
commands:
  PluginLimiter:
    aliases:
      - pl
    description: Commands for PluginLimiter