name: PluginLimiter
main: top.iseason.bukkit.PluginLimiter
description: "限制插件功能"
version: 1.2
authors: [ Iseason ]
commands:
  PluginLimiter:
    aliases:
      - pl
      - plr
      - pnl
    description: Commands for PluginLimiter